name: Pushing website on S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Zipping
        run: |
          cd FrontEnd  
          zip -r FrontEnd.zip ./*
          mv FrontEnd.zip ../frontEnd.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontEnd-zip
          path: frontEnd.zip  

      - name: Configure AWS Credentials
        run: |
          mkdir -p $HOME/.aws
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
          aws configure set default.region ap-south-1  # Replace with your preferred AWS region

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontEnd-zip

      - name: Upload to S3
        run: |
          aws s3 cp frontEnd.zip s3://rahul-bucket-1996/frontEnd-zip.zip  # Replace 'rahul-bucket-1996' with your actual S3 bucket name
