name: Pushing website on S3

on:
  push:
    branches:
      - main

# permissions:
#   id-token: write
#   contents: read
#   actions: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Zipping
        run: |
          cd FrontEnd  
          zip -r FrontEnd.zip ./*
          mv FrontEnd.zip ../frontEnd.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontEnd-zip
          path: frontEnd.zip  

      # - name: Configure AWS Credentials
      #   run: |
      #     mkdir -p $HOME/.aws
      #     echo "[default]" >> $HOME/.aws/credentials
      #     echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
      #     echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
      #     aws configure set default.region ap-south-1  
      - name: Configure AWS credentials
        id: configure-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ReadonlyS3AccessRole
          aws-region: ap-south-1


      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontEnd-zip

      - name: Unzip and Upload to S3
        run: |
          unzip -q frontEnd.zip -d extracted_content
          aws s3 sync extracted_content s3://rahul-bucket-1996/